builds:
  - binary: vin
    goos:
      - darwin
      - linux
    goarch:
      - amd64

brew:
  name: vin

  github:
    owner: benfb
    name: homebrew-tap

  homepage: "https://github.com/benfb/vin/"
  description: "Simple baseball CLI."